server:
  port: 8080
spring:
  activiti:
    check-process-definitions: true
  datasource:
    url: jdbc:mysql://localhost:3306/workflow?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver